import { SRC } from "./sources";

export type Era = "origins" | "first-flights" | "service" | "records" | "tragedy" | "retirement" | "successors";

export interface TimelineEntry {
  year: number;
  /** Human-readable day, e.g. "29 Nov". Omitted when only the year is established. */
  date?: string;
  title: string;
  detail: string;
  era: Era;
  source: string;
  /** Major beats the rail should emphasise. */
  highlight?: boolean;
}

export const ERA_LABELS: Record<Era, string> = {
  origins: "Origins",
  "first-flights": "First flights",
  service: "In service",
  records: "Records",
  tragedy: "Gonesse",
  retirement: "Retirement",
  successors: "What comes next",
};

export const TIMELINE: readonly TimelineEntry[] = [
  {
    year: 1954,
    title: "A question at Farnborough",
    detail: "The Royal Aircraft Establishment asks whether an airliner could cruise faster than sound. Morien Morgan is told to find out.",
    era: "origins",
    source: SRC.wiki,
  },
  {
    year: 1956,
    date: "1 Oct",
    title: "STAC convenes",
    detail: "The Supersonic Transport Aircraft Committee begins work on a slender-delta transport for Mach 2.",
    era: "origins",
    source: SRC.wiki,
  },
  {
    year: 1959,
    title: "The committee reports",
    detail: "STAC recommends two designs: a medium-range Mach 1.2 aircraft and a long-range one for Mach 2. Only the second survives.",
    era: "origins",
    source: SRC.wiki,
  },
  {
    year: 1962,
    date: "29 Nov",
    title: "The treaty",
    detail: "Britain and France sign an international treaty, not a commercial contract, to build the aircraft together. There is no exit clause.",
    era: "origins",
    source: SRC.wiki,
    highlight: true,
  },
  {
    year: 1965,
    title: "Metal is cut",
    detail: "Construction of the two prototypes begins, 001 at Toulouse and 002 at Filton.",
    era: "origins",
    source: SRC.wiki,
  },
  {
    year: 1967,
    date: "11 Dec",
    title: "Concorde, with an e",
    detail: "Prototype 001 is rolled out at Toulouse. Tony Benn confirms the French spelling: e for excellence, England, Europe and entente.",
    era: "origins",
    source: SRC.wiki,
  },
  {
    year: 1968,
    date: "31 Dec",
    title: "Tu-144 flies first",
    detail: "The Soviet Tupolev Tu-144 beats Concorde into the air by two months.",
    era: "origins",
    source: SRC.tu144,
  },
  {
    year: 1969,
    date: "2 Mar",
    title: "001 takes off",
    detail: "André Turcat lifts F-WTSS off the runway at Toulouse-Blagnac, gear down, nose drooped.",
    era: "first-flights",
    source: SRC.list,
    highlight: true,
  },
  {
    year: 1969,
    date: "9 Apr",
    title: "002 follows from Filton",
    detail: "Brian Trubshaw flies the British prototype G-BSST from Filton to RAF Fairford.",
    era: "first-flights",
    source: SRC.list,
  },
  {
    year: 1969,
    date: "1 Oct",
    title: "Through the sound barrier",
    detail: "001 goes supersonic for the first time.",
    era: "first-flights",
    source: SRC.wiki,
  },
  {
    year: 1970,
    title: "Twice the speed of sound",
    detail: "The prototypes reach Mach 2 for the first time, a year after first going supersonic.",
    era: "first-flights",
    source: SRC.wiki,
  },
  {
    year: 1971,
    date: "4 Sep",
    title: "First Atlantic crossing",
    detail: "001 flies Toulouse to Cayenne via Dakar: the first transatlantic Concorde flight.",
    era: "first-flights",
    source: SRC.wiki,
  },
  {
    year: 1971,
    date: "17 Dec",
    title: "Pre-production 101 flies",
    detail: "G-AXDN, the first pre-production aircraft, makes its maiden flight from Filton.",
    era: "first-flights",
    source: SRC.list,
  },
  {
    year: 1973,
    date: "27 Apr",
    title: "America bans the boom",
    detail: "The United States prohibits civil supersonic flight over land. The rule, 14 CFR 91.817, is still in force.",
    era: "first-flights",
    source: SRC.cfr91817,
  },
  {
    year: 1973,
    date: "3 Jun",
    title: "Tu-144 crashes at Paris",
    detail: "The Soviet rival breaks up in flight during a display at the Paris Air Show.",
    era: "first-flights",
    source: SRC.tu144,
  },
  {
    year: 1974,
    date: "26 Mar",
    title: "Mach 2.23",
    detail: "G-AXDN reaches 2,370 km/h, the fastest any Concorde ever flew.",
    era: "records",
    source: SRC.wiki,
  },
  {
    year: 1976,
    date: "21 Jan",
    title: "Into service",
    detail: "At 11:40 BA300 pushes back from Heathrow for Bahrain and AF025 from Paris for Rio, simultaneously.",
    era: "service",
    source: SRC.heritage,
    highlight: true,
  },
  {
    year: 1976,
    date: "24 May",
    title: "Washington Dulles",
    detail: "Air France and British Airways begin a thrice-weekly service to Dulles on the same day.",
    era: "service",
    source: SRC.ops,
  },
  {
    year: 1977,
    date: "22 Nov",
    title: "New York at last",
    detail: "The JFK ban ends on 17 October when the Supreme Court declines to intervene. Scheduled service begins five weeks later.",
    era: "service",
    source: SRC.ops,
    highlight: true,
  },
  {
    year: 1978,
    date: "1 Jun",
    title: "Tu-144 retires",
    detail: "Soviet passenger service ends after 55 flights.",
    era: "service",
    source: SRC.tu144,
  },
  {
    year: 1978,
    date: "Dec",
    title: "Braniff interchange",
    detail: "Braniff leases Concordes for a subsonic Dallas to Washington leg, until May 1980.",
    era: "service",
    source: SRC.ops,
  },
  {
    year: 1985,
    date: "13 Jul",
    title: "Live Aid on both continents",
    detail: "Phil Collins plays Wembley, boards Concorde, and plays Philadelphia the same evening.",
    era: "service",
    source: SRC.liveAid,
    highlight: true,
  },
  {
    year: 1985,
    date: "24 Dec",
    title: "Four in formation",
    detail: "Four British Airways Concordes fly in formation for a Christmas Eve photograph.",
    era: "service",
    source: SRC.heritage,
  },
  {
    year: 1992,
    date: "12 Oct",
    title: "Westward round the world",
    detail: "Air France circles the globe westbound in 32 h 49 m to mark the 500th anniversary of Columbus.",
    era: "records",
    source: SRC.ops,
  },
  {
    year: 1995,
    date: "15 Aug",
    title: "Fastest circumnavigation",
    detail: "Air France flies around the world eastbound in 31 h 27 m 49 s.",
    era: "records",
    source: SRC.guinness,
    highlight: true,
  },
  {
    year: 1996,
    date: "7 Feb",
    title: "The Atlantic in under three hours",
    detail: "G-BOAD flies New York to London in 2 h 52 m 59 s. The record still stands.",
    era: "records",
    source: SRC.guinness,
    highlight: true,
  },
  {
    year: 2000,
    date: "25 Jul",
    title: "Gonesse",
    detail: "Air France 4590 crashes after take-off from Paris. 113 people die. The fleet is grounded within weeks.",
    era: "tragedy",
    source: SRC.af4590,
    highlight: true,
  },
  {
    year: 2001,
    date: "5 Sep",
    title: "Modified",
    detail: "Kevlar-lined fuel tanks and Michelin NZG tyres are certified.",
    era: "tragedy",
    source: SRC.heritage,
  },
  {
    year: 2001,
    date: "7 Nov",
    title: "Back in the air",
    detail: "Commercial passenger service resumes, eight weeks after 11 September.",
    era: "tragedy",
    source: SRC.ops,
  },
  {
    year: 2002,
    title: "The BEA reports",
    detail: "The French investigation publishes its final account of the chain of events at Gonesse.",
    era: "tragedy",
    source: SRC.af4590,
  },
  {
    year: 2003,
    date: "10 Apr",
    title: "Retirement announced",
    detail: "British Airways and Air France announce the end together. Airbus had withdrawn support.",
    era: "retirement",
    source: SRC.heritage,
    highlight: true,
  },
  {
    year: 2003,
    date: "31 May",
    title: "Air France bows out",
    detail: "AF001 from New York is the last Air France commercial flight.",
    era: "retirement",
    source: SRC.ops,
  },
  {
    year: 2003,
    date: "27 Jun",
    title: "The last French flight",
    detail: "F-BVFC flies Paris to Toulouse, back to where 001 first flew.",
    era: "retirement",
    source: SRC.ops,
  },
  {
    year: 2003,
    date: "24 Oct",
    title: "Three land at Heathrow",
    detail: "G-BOAE, G-BOAF and G-BOAG land in sequence. Captain Mike Bannister's BA002 from New York touches down at 16:05.",
    era: "retirement",
    source: SRC.retirement,
    highlight: true,
  },
  {
    year: 2003,
    date: "26 Nov",
    title: "The last flight",
    detail: "G-BOAF flies Heathrow to Filton, supersonic over the Atlantic, before more than 20,000 people.",
    era: "retirement",
    source: SRC.ops,
    highlight: true,
  },
  {
    year: 2025,
    date: "28 Jan",
    title: "Boom XB-1 goes supersonic",
    detail: "The first privately developed jet to break the sound barrier.",
    era: "successors",
    source: SRC.xb1,
  },
  {
    year: 2025,
    date: "28 Oct",
    title: "X-59 first flight",
    detail: "NASA's quiet-supersonic demonstrator flies for the first time.",
    era: "successors",
    source: SRC.x59,
  },
  {
    year: 2026,
    date: "5 Jun",
    title: "X-59 breaks the barrier",
    detail: "The demonstrator reaches about Mach 1, built to turn the boom into a thump.",
    era: "successors",
    source: SRC.x59,
  },
  {
    year: 2026,
    date: "2 Jul",
    title: "The ban reconsidered",
    detail: "The FAA proposes lifting the 1973 prohibition on overland supersonic flight.",
    era: "successors",
    source: SRC.faaSupersonic,
    highlight: true,
  },
];
